// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlXAP20EO2fkMJdF0kvA3U0fmlSp1ubx0',
    appId: '1:334491000577:android:0b581636c0bd537196c500',
    messagingSenderId: '334491000577',
    projectId: 'drivebuddy-8590c',
    storageBucket: 'drivebuddy-8590c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ITfKEwd4Oa8WqwIPvicKQWWsXhU_u7c',
    appId: '1:334491000577:ios:9060cbecc40e332b96c500',
    messagingSenderId: '334491000577',
    projectId: 'drivebuddy-8590c',
    storageBucket: 'drivebuddy-8590c.firebasestorage.app',
    iosBundleId: 'com.example.drivebuddy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-W1BMBs4HMlJLXz-ctyiOY3S2t_FESTI',
    appId: '1:334491000577:web:f9fb52283e76e3e596c500',
    messagingSenderId: '334491000577',
    projectId: 'drivebuddy-8590c',
    authDomain: 'drivebuddy-8590c.firebaseapp.com',
    storageBucket: 'drivebuddy-8590c.firebasestorage.app',
  );

}